### ISSUE TITLE
Orchestration Service URL is not accessible

### ISSUE THREAD

**Issue by Kartik-Rai** [IHTSDO/orchestration-service#1]
Hi there!

Hope you all are safe and doing well.

After starting the orchestration service, I tried to access the service using the port 9007 but there is no page for the API documentation. 
So my question Is the service accessible using the port or it is running without having any API documentation ?

Thanks & Regards
Kartik Rai (NRC India)

**Comment by kaicode** [comment]
Hi @Kartik-Rai,

Unfortunately the API has no Swagger documentation. Please refer the the REST controller source code for some direction. 

We plan to remove the Orchestration Service in the next year or so. The Authoring Platform validation functions will probably be moved to the Authoring Services component. The other functions are for integration with release process, they will be moved to the Snomed Release Service.

Kind regards,
Kai Kewley

**Comment by Kartik-Rai** [comment]
@kaicode Okay, great!
